# Copy this file to .streamlit/secrets.toml and fill in your values
# DO NOT commit secrets.toml to GitHub!

MONGO_URI = "mongodb://jimmypage:alltheglitterisgold%409899@zlearn.in:27017/?tls=false"
DB_NAME = "nism-platform"
